# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulUsers_app', '0002_auto_20171019_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
